# Generated by Django 5.2.3 on 2025-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0002_alter_workspaceuserresourcepermission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceuserresourcepermission',
            name='auth_target_type',
            field=models.CharField(choices=[('KNOWLEDGE', '知识库'), ('APPLICATION', '应用'), ('TOOL', '工具'), ('MODEL', '模型')], default='KNOWLEDGE', max_length=128, verbose_name='授权目标'),
        ),
    ]
