# Generated by Django 5.2.3 on 2025-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='workspace_id',
            field=models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id'),
        ),
    ]
