# Generated by Django 6.0.7 on 2026-08-03 02:04

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0005_resourcemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='nick_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='昵称'),
        ),
        migrations.CreateModel(
            name='ChatUserApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('secret_key', models.CharField(max_length=1024, unique=True, verbose_name='秘钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否开启')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.chatuser', verbose_name='用户')),
            ],
            options={
                'db_table': 'chat_user_api_key',
            },
        ),
    ]
