# Generated by Django 6.0.7 on 2026-07-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0005_resourcemapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuser",
            name="nick_name",
            field=models.CharField(db_index=True, max_length=150, verbose_name="昵称"),
        ),
    ]
