# Generated by Django 6.0.7 on 2026-08-06 02:40

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0007_workspaceusergroupresourcepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUserTokenQuota',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户id')),
                ('quota_type', models.CharField(choices=[('UNLIMITED', '不限额'), ('PERIODIC', '按周期限制')], default='UNLIMITED', max_length=20, verbose_name='配额模式')),
                ('period_type', models.CharField(blank=True, choices=[('DAY', '天'), ('WEEK', '周'), ('MONTH', '月')], max_length=10, null=True, verbose_name='周期单位')),
                ('period_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='周期数量')),
                ('token_limit', models.BigIntegerField(blank=True, null=True, verbose_name='Tokens上限')),
                ('used_tokens', models.BigIntegerField(default=0, verbose_name='当前周期已使用Tokens')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='累计Tokens')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='当前周期开始时间')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='当前周期结束时间')),
            ],
            options={
                'db_table': 'chat_user_token_quota',
            },
        ),
    ]
