version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
      day: "friday"
    target-branch: "v2"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
      day: "friday"
    target-branch: "main"
