version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: '13:52'
#      day: "friday"
    target-branch: v2