# Generated by Django 4.1.10 on 2024-01-16 11:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='star_num',
        ),
        migrations.RemoveField(
            model_name='embedding',
            name='trample_num',
        ),
        migrations.AddField(
            model_name='embedding',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None, verbose_name='关键词列表'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='source_type',
            field=models.CharField(choices=[('0', '问题'), ('1', '段落'), ('2', '标题')], default='0', max_length=5, verbose_name='资源类型'),
        ),
    ]
