# Generated by Django 4.1.10 on 2023-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='star_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='trample_num',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
    ]
