# Generated by Django 4.2.14 on 2024-07-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_embedding_search_vector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together=set(),
        ),
    ]
