# Generated by Django 4.1.10 on 2023-11-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_embedding_star_num_embedding_trample_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('source_id', 'source_type')},
        ),
    ]
