# Generated by Django 4.1.10 on 2023-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0004_alter_embedding_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='source_type',
            field=models.CharField(choices=[('0', '问题'), ('1', '段落')], default='0', max_length=5, verbose_name='资源类型'),
        ),
    ]
