/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MkComplexSearch: typeof import('./components/global/mk-complex-search/index.vue')['default']
    MkDrawer: typeof import('./components/global/mk-drawer/index.vue')['default']
    MkDropdown: typeof import('./components/global/mk-dropdown/index.vue')['default']
    MkDropdownItem: typeof import('./components/global/mk-dropdown/mk-dropdown-item.vue')['default']
    MkDropdownMenu: typeof import('./components/global/mk-dropdown/mk-dropdown-menu.vue')['default']
    MkFilterableDropdown: typeof import('./components/global/mk-filterable-dropdown/index.vue')['default']
    MkIcon: typeof import('./components/global/mk-icon/index.vue')['default']
    MkSearchInput: typeof import('./components/global/mk-search-input/index.vue')['default']
    MkStatusLabel: typeof import('./components/global/mk-status-label/index.vue')['default']
    MkTable: typeof import('./components/global/mk-table/index.vue')['default']
    MkTagGroup: typeof import('./components/global/mk-tag-group/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const MkComplexSearch: typeof import('./components/global/mk-complex-search/index.vue')['default']
  const MkDrawer: typeof import('./components/global/mk-drawer/index.vue')['default']
  const MkDropdown: typeof import('./components/global/mk-dropdown/index.vue')['default']
  const MkDropdownItem: typeof import('./components/global/mk-dropdown/mk-dropdown-item.vue')['default']
  const MkDropdownMenu: typeof import('./components/global/mk-dropdown/mk-dropdown-menu.vue')['default']
  const MkFilterableDropdown: typeof import('./components/global/mk-filterable-dropdown/index.vue')['default']
  const MkIcon: typeof import('./components/global/mk-icon/index.vue')['default']
  const MkSearchInput: typeof import('./components/global/mk-search-input/index.vue')['default']
  const MkStatusLabel: typeof import('./components/global/mk-status-label/index.vue')['default']
  const MkTable: typeof import('./components/global/mk-table/index.vue')['default']
  const MkTagGroup: typeof import('./components/global/mk-tag-group/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}