"""MCP egress policy shared by validation, discovery and tool execution."""

from functools import partial

from langchain_mcp_adapters.client import MultiServerMCPClient

from common.utils.mcp_network import http_client_factory, parse_url


class InternalMCPConfig(dict):
    """In-memory provenance for configurations generated by ToolExecutor.

    Never deserialize user input into this type. JSON round trips deliberately
    lose this privilege; keep runtime configurations in memory instead.
    """


def validate_mcp_servers(servers):
    if not isinstance(servers, dict):
        raise ValueError("MCP servers must be an object")
    for config in servers.values():
        if not isinstance(config, dict) or config.get("transport") not in ("sse", "streamable_http"):
            raise ValueError("Only support transport=sse or transport=streamable_http")
        # Do not resolve or connect in the web process. sandbox.so enforces
        # hostname and address restrictions when the worker opens a connection.
        parse_url(config.get("url"))


def create_mcp_client(servers):
    if not isinstance(servers, dict):
        raise ValueError("MCP servers must be an object")
    connections = {}
    for name, config in servers.items():
        if not isinstance(config, dict):
            raise ValueError("MCP server configuration must be an object")
        internal = isinstance(config, InternalMCPConfig)
        if internal and config.get("transport") == "stdio":
            connections[name] = dict(config)
            continue
        if config.get("transport") not in ("sse", "streamable_http"):
            raise ValueError("Only support transport=sse or transport=streamable_http")
        url = parse_url(config.get("url"))
        if internal:
            connection = dict(config)
            connection["httpx_client_factory"] = partial(
                http_client_factory, url=str(url), internal=True,
            )
        else:
            from common.utils.mcp_sandbox import sandbox_connection

            connection = sandbox_connection(config)
        connections[name] = connection
    return MultiServerMCPClient(connections)
