# Generated by Django 6.0.7 on 2026-07-27 07:06

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.UUIDField(default=uuid_utils.compat.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="id",
            field=models.UUIDField(default=uuid_utils.compat.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
