import { Permission, Role, Edition } from '@/utils/permission/type'
// class Operate(Enum):
//     """
//      一个权限组的操作权限
//     """
//     READ = 'READ'
//     EDIT = "READ+EDIT"
//     CREATE = "READ+CREATE"
//     DELETE = "READ+DELETE"
//     """
//     使用权限
//     """
//     USE = "USE"
//     IMPORT = "READ+IMPORT"
//     EXPORT = "READ+EXPORT"  # 导入导出
//     DEBUG = "READ+DEBUG"  # 调试
//     SYNC = "READ+SYNC"  # 同步
//     GENERATE = "READ+GENERATE"  # 生成
//     ADD_MEMBER = "READ+ADD_MEMBER"  # 添加成员
//     REMOVE_MEMBER = "READ+REMOVE_MEMBER"  # 添加成员
//     VECTOR = "READ+VECTOR"  # 向量化
//     MIGRATE = "READ+MIGRATE"  # 迁移
//     RELATE = "READ+RELATE"  # 关联
//     USER_GROUP = "READ+USER_GROUP"  # 用户组
//     ANNOTATION = "READ+ANNOTATION"  # 标注
//     CLEAR_POLICY = "READ+CLEAR_POLICY"
const PermissionConst = {
  USER_READ: new Permission('USER:READ'),
  USER_CREATE: new Permission('USER:CREATE'),

  KNOWLEDGE_READ: new Permission('KNOWLEDGE:READ'),
  KNOWLEDGE_CREATE: new Permission('KNOWLEDGE:READ+CREATE'),
  KNOWLEDGE_SYNC: new Permission('KNOWLEDGE:READ+SYNC'),
  KNOWLEDGE_VECTOR: new Permission('KNOWLEDGE:READ+VECTOR'),
  KNOWLEDGE_EDIT: new Permission('KNOWLEDGE:READ+EDIT'),
  KNOWLEDGE_EXPORT: new Permission('KNOWLEDGE:READ+EXPORT'),
  KNOWLEDGE_DELETE: new Permission('KNOWLEDGE:READ+DELETE'),

  KNOWLEDGE_DOCUMENT_READ:new Permission('KNOWLEDGE_DOCUMENT:READ'),
  KNOWLEDGE_DOCUMENT_CREATE:new Permission('KNOWLEDGE_DOCUMENT:READ+CREATE'),
  KNOWLEDGE_DOCUMENT_EDIT:new Permission('KNOWLEDGE_DOCUMENT:READ+EDIT'),
  KNOWLEDGE_DOCUMENT_SYNC:new Permission('KNOWLEDGE_DOCUMENT:READ+SYNC'),
  KNOWLEDGE_DOCUMENT_MIGRATE:new Permission('KNOWLEDGE_DOCUMENT:READ+MIGRATE'),
  KNOWLEDGE_DOCUMENT_VECTOR:new Permission('KNOWLEDGE_DOCUMENT:READ+VECTOR'),
  KNOWLEDGE_DOCUMENT_GENERATE:new Permission('KNOWLEDGE_DOCUMENT:READ+GENERATE'),
  KNOWLEDGE_DOCUMENT_EXPORT:new Permission('KNOWLEDGE_DOCUMENT:READ+EXPORT'),

  KNOWLEDGE_PROBLEM_READ:new Permission('KNOWLEDGE_PROBLEM:READ'),
  KNOWLEDGE_PROBLEM_CREATE:new Permission('KNOWLEDGE_PROBLEM:READ+CREATE'),
  KNOWLEDGE_PROBLEM_EDIT:new Permission('KNOWLEDGE_PROBLEM:READ+EDIT'),
  KNOWLEDGE_PROBLEM_RELATE:new Permission('KNOWLEDGE_PROBLEM:READ+RELATE'),
  KNOWLEDGE_PROBLEM_DELETE:new Permission('KNOWLEDGE_PROBLEM:READ+DELETE'),

  MODEL_READ:new Permission('MODEL:READ'),
  MODEL_CREATE:new Permission('MODEL:READ+CREATE'),
  MODEL_EDIT:new Permission('MODEL:READ+EDIT'),
  MODEL_DELETE:new Permission('MODEL:READ+DELETE'),

  APPLICATION_READ:new Permission('APPLICATION:READ'),
  APPLICATION_EXPORT:new Permission('APPLICATION:READ+EXPORT'),
  APPLICATION_DELETE:new Permission('APPLICATION:READ+DELETE'),
  APPLICATION_EDIT:new Permission('APPLICATION:READ+EDIT'),
  
  APPLICATION_OVERVIEW_READ:new Permission('OVERVIEW:READ'),
  APPLICATION_OVERVIEW_EMBEDDED:new Permission('OVERVIEW:READ'),
  APPLICATION_OVERVIEW_ACCESS:new Permission('OVERVIEW:READ'),
  APPLICATION_OVERVIEW_DISPLAY:new Permission('OVERVIEW:READ'),
  APPLICATION_OVERVIEW_API_KEY:new Permission('OVERVIEW:READ'),
  APPLICATION_OVERVIEW_PUBLIC:new Permission('OVERVIEW:READ'),

  APPLICATION_CHAT_LOG:new Permission('APPLICATION_CHAT_LOG:READ'), 
  APPLICATION_CHAT_LOG_ANNOTATION:new Permission('APPLICATION_CHAT_LOG:READ+ANNOTATION'), 
  APPLICATION_CHAT_LOG_EXPORT:new Permission('APPLICATION_CHAT_LOG:READ+EXPORT'),
  APPLICATION_CHAT_LOG_POLICY:new Permission('APPLICATION_CHAT_LOG:READ+CLEAR_POLICY'),
  
  APPLICATION_ACCESS_READ:new Permission('APPLICATION_CHAT_LOG:READ'),
  APPLICATION_ACCESS_EDIT:new Permission('APPLICATION_CHAT_LOG:READ+EDIT'),

  SHARED_TOOL_READ:new Permission('SYSTEM_TOOL:READ'),
  SHARED_TOOL_CREATE:new Permission('SYSTEM_TOOL:READ+CREATE'),
  SHARED_TOOL_EDIT:new Permission('SYSTEM_TOOL:READ+EDIT'),
  SHARED_TOOL_DELETE:new Permission('SYSTEM_TOOL:READ+DELETE'),
  SHARED_TOOL_IMPORT:new Permission('SYSTEM_TOOL:READ+IMPORT'),
  SHARED_TOOL_EXPORT:new Permission('SYSTEM_TOOL:READ+EXPORT'),
  SHARED_TOOL_DEBUG:new Permission('SYSTEM_TOOL:READ+DEBUG'),

  TOOL_CREATE:new Permission('TOOL:READ+CREATE'),
  TOOL_EDIT:new Permission('TOOL:READ+EDIT'),
  TOOL_READ:new Permission('TOOL:READ'),
  TOOL_DELETE:new Permission('TOOL:READ+DELETE'),
  TOOL_DEBUG:new Permission('TOOL:READ+DEBUG'),
  TOOL_IMPORT:new Permission('TOOL:READ+IMPORT'),
  TOOL_EXPORT:new Permission('TOOL:READ+EXPORT'),

  RESOURCE_TOOL_CREATE:new Permission('SYSTEM_RES_TOOL:READ+CREATE'),
  RESOURCE_TOOL_EDIT:new Permission('SYSTEM_RES_TOOL:READ+EDIT'),
  RESOURCE_TOOL_READ:new Permission('SYSTEM_RES_TOOL:READ'),
  RESOURCE_TOOL_DELETE:new Permission('SYSTEM_RES_TOOL:READ+DELETE'),
  RESOURCE_TOOL_DEBUG:new Permission('SYSTEM_RES_TOOL:READ+DEBUG'),
  RESOURCE_TOOL_IMPORT:new Permission('SYSTEM_RES_TOOL:READ+IMPORT'),
  RESOURCE_TOOL_EXPORT:new Permission('SYSTEM_RES_TOOL:READ+EXPORT'),

  WORKSPACE_ROLE_READ:new Permission('WORKSAPCE_ROLE:READ'),
  WORKSPACE_ROLE_ADD_MEMBER:new Permission('WORKSAPCE_ROLE:READ+ADD_MEMBER'),
  WORKSPACE_ROLE_REMOVE_MEMBER:new Permission('WORKSAPCE_ROLE:READ+REMOVE_MEMBER'),
 






  SYSTEM_API_KEY_EDIT:new Permission('OTHER: READ+EDIT')



}
const RoleConst = {
  ADMIN: new Role('ADMIN'),
  WORKSPACE_MANAGE: new Role('WORKSPACE_MANAGE'),
  USER: new Role('USER'),
}
const EditionConst = {
  IS_PE: new Edition('X-PACK-PE'),
  IS_EE: new Edition('X-PACK-EE'),
  IS_CE: new Edition('X-PACK-CE'),
}
export { PermissionConst, RoleConst, EditionConst }
