/** 对话日志的发起来源。 */
export const CHAT_LOG_SOURCE = {
  ONLINE: 'ONLINE',
  API_CALL: 'API_CALL',
  ENTERPRISE_WECHAT: 'ENTERPRISE_WECHAT',
  WECHAT_PUBLIC_ACCOUNT: 'WECHAT_PUBLIC_ACCOUNT',
  LARK: 'LARK',
  DINGTALK: 'DINGTALK',
  ENTERPRISE_WECHAT_ROBOT: 'ENTERPRISE_WECHAT_ROBOT',
  TRIGGER: 'TRIGGER',
  SLACK: 'SLACK',
} as const
