/** 文件上传的资源归属及临时文件有效期。 */
export const FILE_SOURCE_TYPE = {
  KNOWLEDGE: 'KNOWLEDGE',
  APPLICATION: 'APPLICATION',
  TOOL: 'TOOL',
  DOCUMENT: 'DOCUMENT',
  CHAT: 'CHAT',
  TEMPORARY_30_MINUTE: 'TEMPORARY_30_MINUTE',
  TEMPORARY_120_MINUTE: 'TEMPORARY_120_MINUTE',
  TEMPORARY_1_DAY: 'TEMPORARY_1_DAY',
} as const
