/** 跨业务复用的任务状态，按需扩展。 */
export const STATE_TYPES = {
  PENDING: 'PENDING',
  STARTED: 'STARTED',
  EMBEDDING: 'EMBEDDING',
  GENERATE: 'GENERATE',
  SYNC: 'SYNC',
  TOKENIZE: 'TOKENIZE',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  REVOKE: 'REVOKE',
  REVOKED: 'REVOKED',
  TRIGGER_ERROR: 'TRIGGER_ERROR',
} as const
