# Generated by Django 5.2.3 on 2025-06-20 03:43
import os

from django.db import migrations, models
from common.utils.common import get_file_content
from maxkb.conf import PROJECT_DIR

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='label',
            field=models.CharField(max_length=128, null=True, verbose_name='标签'),
        ),
        # migrations.RunSQL(get_file_content(os.path.join(PROJECT_DIR, "apps", "tools", 'migrations', 'internal_tool.sql')))
    ]
