# Generated by Django 5.2.4 on 2025-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='template_id',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True, verbose_name='模版id'),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='版本号'),
        ),
    ]
