# Generated by Django 5.2.8 on 2025-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('INTERNAL', '内置'), ('CUSTOM', '自定义'), ('MCP', 'MCP工具'), ('DATA_SOURCE', '数据源')], db_index=True, default='CUSTOM', max_length=20, verbose_name='工具类型'),
        ),
    ]
