# Generated by Django 5.2.16 on 2026-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_tool_tool_type_toolworkflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolworkflow',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
        migrations.AddField(
            model_name='toolworkflowversion',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('INTERNAL', '内置'), ('CUSTOM', '自定义'), ('SKILL', '技能'), ('MCP', 'MCP工具'), ('DATA_SOURCE', '数据源'), ('WORKFLOW', '工作流')], db_index=True, default='CUSTOM', max_length=20, verbose_name='工具类型'),
        ),
        migrations.AlterField(
            model_name='toolrecord',
            name='source_type',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('KNOWLEDGE', 'Knowledge'), ('TOOL', 'Tool'), ('TRIGGER', 'Trigger')], default='APPLICATION', max_length=256, verbose_name='触发器任务类型'),
        ),
    ]
