# Generated by Django 4.2.15 on 2025-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_lib', '0002_functionlib_is_active_functionlib_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionlib',
            name='icon',
            field=models.CharField(default='/ui/favicon.ico', max_length=256, verbose_name='函数库icon'),
        ),
        migrations.AddField(
            model_name='functionlib',
            name='init_field_list',
            field=models.JSONField(default=list, verbose_name='启动字段列表'),
        ),
    ]
