blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/1Panel-dev/MaxKB/discussions
    about: Raise questions about the installation, deployment, use and other aspects of the project.