name: 'Feature Request'
description: 'Suggest an idea'
title: '[Feature] '
assignees: baixin513
body:
  - type: markdown
    attributes:
      value: "## Environment Information"
  - type: input
    validations:
      required: true
    attributes:
      label: "MaxKB Version"
      description: "Log in to the MaxKB Web Console and check the current version on the `About` page in the top right corner."
  - type: markdown
    attributes:
      value: "## Detailed information"
  - type: textarea
    attributes:
      label: "Please describe your needs or suggestions for improvements"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Please describe the solution you suggest"
  - type: textarea
    attributes:
      label: "Additional Information"
      description: "If you have any additional information to provide, you can include it here (screenshots, videos, etc., are welcome)."