# Generated by Django 5.2 on 2025-04-25 06:42

import django.db.models.deletion
import knowledge.models.knowledge
import mptt.fields
import uuid_utils.compat
from django.db import migrations, models

from knowledge.models import KnowledgeFolder


def insert_default_data(apps, schema_editor):
    # 创建一个根模块（没有父节点）
    KnowledgeFolder.objects.create(id='root', name='根目录', user_id='f0dd8f71-e4ee-11ee-8c84-a8a1595801ab')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('models_provider', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id',
                 models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False,
                                  verbose_name='主键id')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名称')),
                ('workspace_id',
                 models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id')),
                ('loid', models.IntegerField(verbose_name='loid')),
                ('meta', models.JSONField(default=dict, verbose_name='文件关联数据')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFolder',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False,
                                        verbose_name='主键id')),
                ('name', models.CharField(max_length=64, verbose_name='文件夹名称')),
                ('workspace_id',
                 models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            related_name='children', to='knowledge.knowledgefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user',
                                           verbose_name='用户id')),
            ],
            options={
                'db_table': 'knowledge_folder',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id',
                 models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False,
                                  verbose_name='主键id')),
                ('name', models.CharField(max_length=150, verbose_name='知识库名称')),
                ('workspace_id',
                 models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id')),
                ('desc', models.CharField(max_length=256, verbose_name='描述')),
                ('type',
                 models.IntegerField(choices=[(0, '通用类型'), (1, 'web站点类型'), (2, '飞书类型'), (3, '语雀类型')],
                                     default=0, verbose_name='类型')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('scope',
                 models.CharField(choices=[('SHARED', '共享'), ('WORKSPACE', '工作空间可用')], default='WORKSPACE',
                                  max_length=20, verbose_name='可用范围')),
                ('folder',
                 models.ForeignKey(default='root', on_delete=django.db.models.deletion.DO_NOTHING,
                                   to='knowledge.knowledgefolder',
                                   verbose_name='文件夹id')),
                ('embedding_model', models.ForeignKey(default=knowledge.models.knowledge.default_model,
                                                     on_delete=django.db.models.deletion.DO_NOTHING,
                                                     to='models_provider.model', verbose_name='向量模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user',
                                           verbose_name='所属用户')),
            ],
            options={
                'db_table': 'knowledge',
            },
        ),
        migrations.RunPython(insert_default_data),
    ]
