# Generated by Django 5.2.3 on 2025-06-26 03:39

import django.db.models.deletion
import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('models_provider', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.get_default_status, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='embedding_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_provider.model'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.get_default_status, max_length=20, verbose_name='状态'),
        ),
    ]
