# Generated by Django 5.2.1 on 2025-06-06 03:59

import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_document_status_alter_file_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='file_count_limit',
            field=models.IntegerField(default=50, verbose_name='文件数量限制'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
    ]
