# Generated by Django 5.2.3 on 2025-07-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source_id',
            field=models.CharField(default='TEMPORARY_120_MINUTE', verbose_name='资源id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_type',
            field=models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('APPLICATION', 'Application'), ('TOOL', 'Tool'), ('DOCUMENT', 'Document'), ('CHAT', 'Chat'), ('TEMPORARY_30_MINUTE', 'Temporary 30 Minute'), ('TEMPORARY_120_MINUTE', 'Temporary 120 Minute'), ('TEMPORARY_1_DAY', 'Temporary 1 Day')], default='TEMPORARY_120_MINUTE', verbose_name='资源类型'),
        ),
    ]
