# Generated by Django 5.2 on 2025-05-06 09:05

import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_document_status_alter_paragraph_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='file_size_limit',
            field=models.IntegerField(default=100, verbose_name='文件大小限制'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
    ]
