# Generated by Django 5.2 on 2025-05-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledge_file_size_limit_alter_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='file',
            name='sha256_hash',
            field=models.CharField(default='', verbose_name='文件sha256_hash标识'),
        ),
        migrations.AddField(
            model_name='file',
            name='source_id',
            field=models.CharField(default='TEMPORARY_100_MINUTE', verbose_name='资源id'),
        ),
        migrations.AddField(
            model_name='file',
            name='source_type',
            field=models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('APPLICATION', 'Application'), ('TEMPORARY_30_MINUTE', 'Temporary 30 Minute'), ('TEMPORARY_100_MINUTE', 'Temporary 120 Minute'), ('TEMPORARY_1_DAY', 'Temporary 1 Day')], default='TEMPORARY_100_MINUTE', verbose_name='资源类型'),
        )
    ]
