# Generated by Django 5.2.3 on 2025-06-17 03:11

import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_document_status_alter_paragraph_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='段落顺序'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
    ]
