# Generated by Django 5.2.1 on 2025-05-14 03:27

import django.db.models.deletion
import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_remove_file_workspace_id_file_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefolder',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='applicationknowledgemapping',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.knowledge'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
    ]
