# Generated by Django 5.2.8 on 2025-11-24 07:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgeaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='chunks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None, verbose_name='块'),
        ),
    ]
