# Generated by Django 5.2.8 on 2025-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_paragraph_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeworkflowversion',
            name='workflow',
        ),
        migrations.AddField(
            model_name='knowledgeworkflowversion',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='版本名称'),
        ),
    ]
