# Generated by Django 5.2 on 2025-05-27 03:05

import knowledge.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_knowledgefolder_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='status',
            field=models.CharField(default=knowledge.models.knowledge.Status.__str__, max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='ApplicationKnowledgeMapping',
        ),
    ]
