# Generated by Django 5.2.14 on 2026-05-15 03:08

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remove_knowledgeworkflowversion_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termbase',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('content', models.CharField(db_index=True, max_length=256, verbose_name='术语内容')),
                ('knowledge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.knowledge')),
            ],
            options={
                'db_table': 'termbase',
            },
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS embedding_search_vector_gin_idx ON embedding USING GIN (search_vector)"
        )
    ]
