# Generated by Django

from django.db import migrations, models
import uuid_utils.compat as uuid
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remove_knowledgeworkflowversion_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageIndexNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('level', models.IntegerField(db_index=True, default=0, verbose_name='层级深度')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='节点标题')),
                ('path', models.JSONField(default=list, verbose_name='完整路径')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='同级排序')),
                ('content', models.TextField(verbose_name='节点内容')),
                ('char_count', models.IntegerField(default=0, verbose_name='字符数')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_nodes', to='knowledge.document')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_nodes', to='knowledge.knowledge')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.pageindexnode')),
            ],
            options={
                'db_table': 'page_index_node',
            },
        ),
        migrations.AddField(
            model_name='embedding',
            name='page_index_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings', to='knowledge.pageindexnode', verbose_name='所属树节点'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='tree_level',
            field=models.IntegerField(default=0, verbose_name='所属层级'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='tree_path',
            field=models.JSONField(default=list, verbose_name='所属路径'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='sibling_index',
            field=models.IntegerField(default=0, verbose_name='兄弟节点索引'),
        ),
    ]
