# Generated by Django 5.2.14 on 2026-07-10 10:44

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFileAccess',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('source_type', models.CharField(choices=[('FILE', '文件'), ('APPLICATION', '应用'), ('KNOWLEDGE', '知识库')], db_index=True, max_length=20, verbose_name='资源类型')),
                ('source_id', models.CharField(db_index=True, max_length=128, verbose_name='资源ID')),
            ],
            options={
                'db_table': 'public_file_access',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='public_file_source__a961f4_idx')],
            },
        ),
    ]
