# Generated by Django 5.2.16 on 2026-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_publicfileaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeworkflow',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
        migrations.AddField(
            model_name='knowledgeworkflowversion',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
    ]
