# Generated by Django 6.1 on 2026-08-13 08:39

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0011_publicfileaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeSyncLog",
            fields=[
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="修改时间")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("workspace_id", models.CharField(db_index=True, max_length=64, verbose_name="工作空间id")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("incremental", "增量同步"), ("replace", "替换同步"), ("complete", "完整同步")],
                        default="incremental",
                        max_length=16,
                        verbose_name="同步方式",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("manual", "手动同步"), ("scheduled", "定时同步")],
                        default="manual",
                        max_length=16,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "同步中"), ("success", "同步成功"), ("failure", "同步失败")],
                        db_index=True,
                        default="running",
                        max_length=16,
                        verbose_name="同步状态",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0, verbose_name="文档总数")),
                ("synced_count", models.PositiveIntegerField(default=0, verbose_name="已同步数")),
                ("skipped_count", models.PositiveIntegerField(default=0, verbose_name="跳过数")),
                ("deleted_count", models.PositiveIntegerField(default=0, verbose_name="删除数")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="失败数")),
                ("duration_ms", models.PositiveBigIntegerField(default=0, verbose_name="耗时毫秒")),
                ("message", models.TextField(blank=True, default="", verbose_name="结果信息")),
            ],
            options={
                "db_table": "knowledge_sync_log",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ParagraphAsset",
            fields=[
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="修改时间")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(db_index=True, default="image", max_length=16, verbose_name="资产类型"),
                ),
                ("position", models.PositiveIntegerField(default=0, verbose_name="段落内位置")),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "手工创建"), ("synced", "外部同步")],
                        default="synced",
                        max_length=16,
                        verbose_name="内容来源",
                    ),
                ),
                (
                    "source_asset_key",
                    models.CharField(db_index=True, default="", max_length=512, verbose_name="远端资产稳定键"),
                ),
                (
                    "source_hash",
                    models.CharField(db_index=True, default="", max_length=64, verbose_name="远端资产哈希"),
                ),
                ("caption", models.TextField(default="", verbose_name="图片标题")),
                ("ocr_text", models.TextField(default="", verbose_name="OCR 文本")),
                ("description", models.TextField(default="", verbose_name="图片描述")),
                (
                    "local_state",
                    models.CharField(
                        choices=[("clean", "未修改"), ("modified", "本地已修改"), ("deleted", "本地已删除")],
                        default="clean",
                        max_length=16,
                        verbose_name="本地状态",
                    ),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[("active", "正常"), ("remote_deleted", "远端已删除"), ("conflict", "同步冲突")],
                        default="active",
                        max_length=24,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("success", "处理成功"),
                            ("failure", "处理失败"),
                            ("skipped", "未启用"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="处理状态",
                    ),
                ),
                ("process_error", models.TextField(default="", verbose_name="处理错误")),
                ("visual_strategy_hash", models.CharField(default="", max_length=64, verbose_name="图片处理策略哈希")),
                ("meta", models.JSONField(default=dict, verbose_name="元数据")),
            ],
            options={
                "db_table": "paragraph_asset",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="doc_strategy",
            field=models.JSONField(default=dict, verbose_name="文档处理策略"),
        ),
        migrations.AddField(
            model_name="document",
            name="hit_num",
            field=models.IntegerField(db_index=True, default=0, verbose_name="召回次数"),
        ),
        migrations.AddField(
            model_name="document",
            name="index_strategy_hash",
            field=models.CharField(default="", max_length=64, verbose_name="索引增强策略哈希"),
        ),
        migrations.AddField(
            model_name="document",
            name="last_hit_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最后一次召回时间"),
        ),
        migrations.AddField(
            model_name="document",
            name="last_sync_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最后同步时间"),
        ),
        migrations.AddField(
            model_name="document",
            name="resource_type",
            field=models.CharField(
                choices=[("document", "文档"), ("image", "图片")],
                db_index=True,
                default="document",
                max_length=16,
                verbose_name="资源类型",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_hash",
            field=models.CharField(db_index=True, default="", max_length=64, verbose_name="远端文档内容哈希"),
        ),
        migrations.AddField(
            model_name="document",
            name="split_strategy_hash",
            field=models.CharField(default="", max_length=64, verbose_name="分段策略哈希"),
        ),
        migrations.AddField(
            model_name="document",
            name="sync_version",
            field=models.PositiveIntegerField(default=0, verbose_name="同步版本"),
        ),
        migrations.AddField(
            model_name="document",
            name="visual_strategy_hash",
            field=models.CharField(default="", max_length=64, verbose_name="图片处理策略哈希"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="anchor_paragraph",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anchored_paragraphs",
                to="knowledge.paragraph",
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="content_schema",
            field=models.JSONField(default=list, verbose_name="结构化内容"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="last_hit_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最后一次召回时间"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="local_state",
            field=models.CharField(
                choices=[("clean", "未修改"), ("modified", "本地已修改"), ("deleted", "本地已删除")],
                db_index=True,
                default="clean",
                max_length=16,
                verbose_name="本地状态",
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="origin",
            field=models.CharField(
                choices=[("manual", "手工创建"), ("synced", "外部同步")],
                db_index=True,
                default="manual",
                max_length=16,
                verbose_name="内容来源",
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="placement",
            field=models.CharField(default="after", max_length=8, verbose_name="相对锚点位置"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="source_hash",
            field=models.CharField(db_index=True, default="", max_length=64, verbose_name="远端内容哈希"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="source_key",
            field=models.CharField(db_index=True, default="", max_length=512, verbose_name="远端稳定键"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="source_snapshot",
            field=models.JSONField(default=dict, verbose_name="上次同步快照"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="远端更新时间"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="sync_state",
            field=models.CharField(
                choices=[("active", "正常"), ("remote_deleted", "远端已删除"), ("conflict", "同步冲突")],
                db_index=True,
                default="active",
                max_length=24,
                verbose_name="同步状态",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="last_hit_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最后一次召回时间"),
        ),
        migrations.AddField(
            model_name="problemparagraphmapping",
            name="meta",
            field=models.JSONField(default=dict, verbose_name="元数据"),
        ),
        migrations.AlterField(
            model_name="embedding",
            name="source_type",
            field=models.CharField(
                choices=[(0, "问题"), (1, "段落"), (2, "标题"), (3, "图片")],
                db_index=True,
                default=0,
                max_length=5,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="hit_num",
            field=models.IntegerField(db_index=True, default=0, verbose_name="召回次数"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="hit_num",
            field=models.IntegerField(db_index=True, default=0, verbose_name="召回次数"),
        ),
        migrations.AddConstraint(
            model_name="paragraph",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("document", "source_key"),
                name="uniq_document_paragraph_source_key",
            ),
        ),
        migrations.AddField(
            model_name="knowledgesynclog",
            name="knowledge",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="knowledge.knowledge",
                verbose_name="知识库",
            ),
        ),
        migrations.AddField(
            model_name="paragraphasset",
            name="document",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="knowledge.document",
            ),
        ),
        migrations.AddField(
            model_name="paragraphasset",
            name="file",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paragraph_assets",
                to="knowledge.file",
            ),
        ),
        migrations.AddField(
            model_name="paragraphasset",
            name="knowledge",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="knowledge.knowledge"
            ),
        ),
        migrations.AddField(
            model_name="paragraphasset",
            name="paragraph",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="knowledge.paragraph",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesynclog",
            index=models.Index(fields=["knowledge", "-create_time"], name="knowledge_s_knowled_9f3ba4_idx"),
        ),
        migrations.AddConstraint(
            model_name="paragraphasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_asset_key", ""), _negated=True),
                fields=("document", "source_asset_key"),
                name="uniq_document_asset_source_key",
            ),
        ),
    ]
