# Generated by Django 6.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0012_multimodal_knowledge_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraphasset",
            name="hit_num",
            field=models.IntegerField(db_index=True, default=0, verbose_name="召回次数"),
        ),
        migrations.AddField(
            model_name="paragraphasset",
            name="last_hit_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最后一次召回时间"),
        ),
    ]
