# Generated by Django 6.1 on 2026-09-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0013_paragraph_asset_recall"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeworkflow",
            name="default_model_setting",
            field=models.JSONField(default=dict, verbose_name="默认模型"),
        ),
        migrations.AddField(
            model_name="knowledgeworkflowversion",
            name="default_model_setting",
            field=models.JSONField(default=dict, verbose_name="默认模型"),
        ),
        migrations.AlterField(
            model_name="file",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("KNOWLEDGE", "Knowledge"),
                    ("APPLICATION", "Application"),
                    ("TOOL", "Tool"),
                    ("DOCUMENT", "Document"),
                    ("CHAT", "Chat"),
                    ("SYSTEM", "System"),
                    ("TEMPORARY_30_MINUTE", "Temporary 30 Minute"),
                    ("TEMPORARY_120_MINUTE", "Temporary 120 Minute"),
                    ("TEMPORARY_1_DAY", "Temporary 1 Day"),
                    ("APPLICATION_SETTINGS", "Application Settings"),
                ],
                db_index=True,
                default="TEMPORARY_120_MINUTE",
                verbose_name="资源类型",
            ),
        ),
    ]
