# Generated by Django 6.0.7 on 2026-08-03 06:20

import uuid_utils.compat
from django.db import migrations, models

def create_default_portal(apps, schema_editor):
    Portal = apps.get_model("portal", "Portal")

    Portal.objects.create(
        name="智能体门户",
        description="默认门户",
        enable_public_access=True,
        enable_api=True,
        enable_auth=False,
        auth_config={},
        enable_cors=False,
        cors_config={},
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('name', models.CharField(default='智能体门户', max_length=64, verbose_name='门户名称')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='门户描述')),
                ('logo', models.CharField(blank=True, max_length=512, null=True, verbose_name='门户Logo地址')),
                ('tab_logo', models.CharField(blank=True, max_length=512, null=True, verbose_name='浏览器Tab Logo地址')),
                ('enable_public_access', models.BooleanField(default=True, verbose_name='是否开启公开访问')),
                ('enable_api', models.BooleanField(default=True, verbose_name='是否开启API服务')),
                ('enable_auth', models.BooleanField(default=False, verbose_name='是否开启身份认证')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='身份认证配置')),
                ('enable_cors', models.BooleanField(default=False, verbose_name='是否开启跨域设置')),
                ('cors_config', models.JSONField(blank=True, default=dict, verbose_name='跨域配置')),
            ],
            options={
                'db_table': 'portal',
            },
        ),
        migrations.RunPython(
            create_default_portal,
            migrations.RunPython.noop,
        ),
    ]
