# Generated by Django 6.0.6 on 2026-07-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='昵称'),
        ),
    ]
