# Generated by Django 5.2 on 2025-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='昵称'),
        ),
    ]
