# Generated by Django 5.2.14 on 2026-08-05 07:06

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUserGroup',
            fields=[
                ('id', models.CharField(default=uuid_utils.compat.uuid7, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='名称')),
                ('workspace_id', models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'system_user_group',
                'unique_together': {('workspace_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SystemUserGroupRelation',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.systemusergroup', verbose_name='用户组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'system_user_group_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='uniq_user_group_relation')],
            },
        ),
    ]
