# Generated by Django 6.0.7 on 2026-08-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_systemusergroup_systemusergrouprelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusergrouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='users.systemusergroup', verbose_name='用户组'),
        ),
    ]
