# Generated by Django 4.2.15 on 2025-01-20 06:59

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default=users.models.user.get_language, max_length=10, verbose_name='语言'),
        ),
    ]
