# Generated by Django 4.2.18 on 2025-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='语言'),
        ),
    ]
