# Generated by Django 4.1.10 on 2023-11-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='provider',
            field=models.CharField(max_length=128, verbose_name='供应商'),
        ),
    ]
