# Generated by Django 4.2.15 on 2024-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_params_form',
            field=models.JSONField(default=list, verbose_name='模型参数配置'),
        ),
    ]
