# Generated by Django 4.2.15 on 2024-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_model_model_params_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='参数')),
                ('field', models.CharField(max_length=256, verbose_name='显示名称')),
                ('default_value', models.CharField(max_length=1000, verbose_name='默认值')),
                ('input_type', models.CharField(max_length=32, verbose_name='组件类型')),
                ('attrs', models.JSONField(verbose_name='属性')),
                ('required', models.BooleanField(verbose_name='必填')),
            ],
        ),
    ]
