# Generated by Django 5.2.4 on 2025-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='chat_background',
            field=models.CharField(default='', max_length=256, verbose_name='聊天背景'),
        ),
        migrations.AddField(
            model_name='application',
            name='avatar',
            field=models.CharField(default='', max_length=256, verbose_name='AI头像'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_avatar',
            field=models.CharField(default='', max_length=256, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='application',
            name='float_icon',
            field=models.CharField(default='', max_length=256, verbose_name='浮窗图标'),
        ),
    ]
