# Generated by Django 5.2.1 on 2025-05-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationknowledgemapping',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.knowledge'),
        ),
    ]
