# Generated by Django 5.2.3 on 2025-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='authentication',
            field=models.BooleanField(default=False, verbose_name='是否需要认证'),
        ),
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='authentication_value',
            field=models.JSONField(default=dict, verbose_name='认证的值'),
        ),
    ]
