# Generated by Django 5.2.4 on 2025-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mcp_enable',
            field=models.BooleanField(default=False, verbose_name='MCP否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='mcp_servers',
            field=models.JSONField(default=dict, verbose_name='MCP服务列表'),
        ),
        migrations.AddField(
            model_name='application',
            name='mcp_source',
            field=models.CharField(default='referencing', max_length=20, verbose_name='MCP Source'),
        ),
        migrations.AddField(
            model_name='application',
            name='mcp_tool_ids',
            field=models.JSONField(default=list, verbose_name='MCP工具ID列表'),
        ),
        migrations.AddField(
            model_name='application',
            name='tool_enable',
            field=models.BooleanField(default=False, verbose_name='工具是否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='tool_ids',
            field=models.JSONField(default=list, verbose_name='工具ID列表'),
        ),
        migrations.AddField(
            model_name='application',
            name='mcp_output_enable',
            field=models.BooleanField(default=True, verbose_name='MCP输出是否启用'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='mcp_enable',
            field=models.BooleanField(default=False, verbose_name='MCP否启用'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='mcp_servers',
            field=models.JSONField(default=dict, verbose_name='MCP服务列表'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='mcp_source',
            field=models.CharField(default='referencing', max_length=20, verbose_name='MCP Source'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='mcp_tool_ids',
            field=models.JSONField(default=list, verbose_name='MCP工具ID列表'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='tool_enable',
            field=models.BooleanField(default=False, verbose_name='工具是否启用'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='tool_ids',
            field=models.JSONField(default=list, verbose_name='工具ID列表'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='mcp_output_enable',
            field=models.BooleanField(default=True, verbose_name='MCP输出是否启用'),
        ),
    ]
