# Generated by Django 5.2.4 on 2025-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_simple_mcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stt_model_params_setting',
            field=models.JSONField(default=dict, verbose_name='STT模型参数相关设置'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='stt_model_params_setting',
            field=models.JSONField(default=dict, verbose_name='STT模型参数相关设置'),
        ),
    ]
