# Generated by Django 5.2.3 on 2025-07-01 02:46

import application.models.application_chat
import common.encoder.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_user_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='asker',
            field=models.JSONField(default=application.models.application_chat.default_asker, encoder=common.encoder.encoder.SystemEncoder, verbose_name='访问者'),
        ),
        migrations.AddField(
            model_name='chat',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='applicationchatuserstats',
            name='chat_user_type',
            field=models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY'), ('PLATFORM_USER', '平台用户')], default='ANONYMOUS_USER', max_length=64, verbose_name='对话用户类型'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_user_id',
            field=models.CharField(default=None, null=True, verbose_name='对话用户id'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_user_type',
            field=models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY'), ('PLATFORM_USER', '平台用户')], default='ANONYMOUS_USER', max_length=64, verbose_name='客户端类型'),
        ),
    ]
