# Generated by Django 5.2 on 2025-06-06 14:56

import django.db.models.deletion
import uuid
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_chat_chatrecord_workflowversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='show_exec',
            field=models.BooleanField(default=False, verbose_name='是否显示执行详情'),
        ),
        migrations.AddField(
            model_name='chat',
            name='client_type',
            field=models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY')], default='ANONYMOUS_USER', max_length=64, verbose_name='客户端类型'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('019745bd-c430-7760-b886-638356133c4b'), editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.CreateModel(
            name='ApplicationChatClientStats',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('client_id', models.UUIDField(default=uuid_utils.compat.uuid7, verbose_name='公共访问链接客户端id')),
                ('client_type', models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY')], default='ANONYMOUS_USER', max_length=64, verbose_name='客户端类型')),
                ('access_num', models.IntegerField(default=0, verbose_name='访问总次数次数')),
                ('intraday_access_num', models.IntegerField(default=0, verbose_name='当日访问次数')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='应用id')),
            ],
            options={
                'db_table': 'application_chat_client_stats',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationPublicAccessClient',
        ),
        migrations.AddIndex(
            model_name='applicationchatclientstats',
            index=models.Index(fields=['application_id', 'client_id'], name='application_applica_f89647_idx'),
        ),
    ]
