# Generated by Django 5.2 on 2025-05-27 03:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicationapikey'),
        ('knowledge', '0007_alter_document_status_alter_paragraph_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAccessToken',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.application', verbose_name='应用id')),
                ('access_token', models.CharField(max_length=128, unique=True, verbose_name='用户公开访问 认证token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否开启公开访问')),
                ('access_num', models.IntegerField(default=100, verbose_name='访问次数')),
                ('white_active', models.BooleanField(default=False, verbose_name='是否开启白名单')),
                ('white_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), default=list, size=None, verbose_name='白名单列表')),
                ('show_source', models.BooleanField(default=False, verbose_name='是否显示知识来源')),
                ('language', models.CharField(default=None, max_length=10, null=True, verbose_name='语言')),
            ],
            options={
                'db_table': 'application_access_token',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.CreateModel(
            name='ApplicationKnowledgeMapping',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.application')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.knowledge')),
            ],
            options={
                'db_table': 'application_knowledge_mapping',
            },
        ),
    ]
