# Generated by Django 5.2 on 2025-06-09 05:55

import uuid
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationaccesstoken_show_exec_chat_client_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicationchatclientstats',
            name='application_applica_f89647_idx',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='client_id',
            new_name='chat_user_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='client_type',
            new_name='chat_user_type',
        ),
        migrations.RemoveField(
            model_name='applicationchatclientstats',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='applicationchatclientstats',
            name='client_type',
        ),
        migrations.AddField(
            model_name='applicationchatclientstats',
            name='chat_user_id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, verbose_name='对话用户id'),
        ),
        migrations.AddField(
            model_name='applicationchatclientstats',
            name='chat_user_type',
            field=models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY')], default='ANONYMOUS_USER', max_length=64, verbose_name='对话用户类型'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01975341-b4e8-7d52-913b-1bb67d7d8107'), editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AddIndex(
            model_name='applicationchatclientstats',
            index=models.Index(fields=['application_id', 'chat_user_id'], name='application_applica_23b4d2_idx'),
        ),
    ]
