# Generated by Django 4.1.10 on 2023-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_chatrecord_dataset_alter_chatrecord_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='source_id',
            field=models.UUIDField(null=True, verbose_name='资源id 段落/问题 id '),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='source_type',
            field=models.CharField(choices=[('0', '问题'), ('1', '段落'), ('-1', '其他')], default='-1', max_length=5, verbose_name='资源类型'),
        ),
    ]
