# Generated by Django 5.2.6 on 2025-09-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_add_display_fields_to_version'),
        ('application', '0003_application_stt_model_params_setting_and_more'),
    ]

    operations = [
    ]
