# Generated by Django 5.2.9 on 2025-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_stt_model_params_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_enable',
            field=models.BooleanField(default=False, verbose_name='应用是否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_ids',
            field=models.JSONField(default=list, verbose_name='应用ID列表'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='application_enable',
            field=models.BooleanField(default=False, verbose_name='应用是否启用'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='application_ids',
            field=models.JSONField(default=list, verbose_name='应用ID列表'),
        ),
    ]
