# Generated by Django 4.1.13 on 2024-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='show_source',
            field=models.BooleanField(default=False, verbose_name='是否显示知识来源'),
        ),
    ]
