# Generated by Django 4.1.10 on 2024-01-15 16:07

import application.models.application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_chatrecord_dataset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='example',
        ),
        migrations.AddField(
            model_name='application',
            name='dataset_setting',
            field=models.JSONField(default=application.models.application.get_dataset_setting_dict, verbose_name='数据集参数设置'),
        ),
        migrations.AddField(
            model_name='application',
            name='model_setting',
            field=models.JSONField(default=application.models.application.get_model_setting_dict, verbose_name='模型参数相关设置'),
        ),
        migrations.AddField(
            model_name='application',
            name='problem_optimization',
            field=models.BooleanField(default=False, verbose_name='问题优化'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='details',
            field=models.JSONField(default={}, verbose_name='对话详情'),
        ),
    ]
