# Generated by Django 5.2 on 2025-06-09 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_applicationchatclientstats_application_applica_f89647_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationChatClientStats',
            new_name='ApplicationChatUserStats',
        ),
        migrations.RenameIndex(
            model_name='applicationchatuserstats',
            new_name='application_applica_1652ba_idx',
            old_name='application_applica_23b4d2_idx',
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01975399-efa5-7dc3-8f97-edc67332ed24'), editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterModelTable(
            name='applicationchatuserstats',
            table='application_chat_user_stats',
        ),
    ]
