# Generated by Django 4.1.10 on 2023-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_chatrecord_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='source_type',
            field=models.CharField(blank=True, choices=[('0', '问题'), ('1', '段落')], default='0', max_length=2, null=True, verbose_name='资源类型'),
        ),
    ]
