# Generated by Django 5.2.8 on 2025-12-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_application_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='vote_other_content',
            field=models.CharField(default='', max_length=1024, verbose_name='其他原因'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='vote_reason',
            field=models.CharField(blank=True, choices=[('accurate', '内容准确'), ('complete', '内容完善'), ('inaccurate', '内容不准确'), ('incomplete', '内容不完善'), ('other', '其他')], max_length=50, null=True, verbose_name='投票原因'),
        ),
    ]
