# Generated by Django 4.1.10 on 2024-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_application_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='details',
            field=models.JSONField(default=dict, verbose_name='对话详情'),
        ),
    ]
