# Generated by Django 5.2.3 on 2025-07-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_publish_time_applicationversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_record_count',
            field=models.IntegerField(default=0, verbose_name='对话次数'),
        ),
        migrations.AddField(
            model_name='chat',
            name='mark_sum',
            field=models.IntegerField(default=0, verbose_name='标记数量'),
        ),
        migrations.AddField(
            model_name='chat',
            name='star_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='chat',
            name='trample_num',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
    ]
