# Generated by Django 5.2.9 on 2026-01-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_merge_20250926_1506'),
        ('application', '0005_chatrecord_vote_other_content_chatrecord_vote_reason'),
    ]

    operations = [
    ]
