# Generated by Django 5.2.3 on 2025-06-18 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_applicationchatclientstats_applicationchatuserstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('019780f8-aeef-7c10-a699-baebbb806ee5'), editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
    ]
