# Generated by Django 4.1.10 on 2024-01-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_chatrecord_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrecord',
            name='paragraph_id_list',
        ),
    ]
