# Generated by Django 4.1.13 on 2024-05-08 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_chat_abstract_alter_chatrecord_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationapikey',
            name='allow_cross_domain',
            field=models.BooleanField(default=False, verbose_name='是否允许跨域'),
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='cross_domain_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), default=list, size=None, verbose_name='跨域列表'),
        ),
    ]
