# Generated by Django 4.1.10 on 2024-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_chatrecord_paragraph_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.CharField(default='', max_length=512, verbose_name='引用描述'),
        ),
    ]
