# Generated by Django 4.1.10 on 2023-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_applicationaccesstoken_applicationapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='api_key_is_active',
            field=models.BooleanField(default=True, verbose_name='api_key是否可用'),
        ),
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.CharField(default='', max_length=128, verbose_name='引用描述'),
        ),
        migrations.AlterField(
            model_name='application',
            name='prologue',
            field=models.CharField(default='', max_length=1024, verbose_name='开场白'),
        ),
    ]
