# Generated by Django 4.1.10 on 2024-03-12 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='access_num',
            field=models.IntegerField(default=100, verbose_name='访问次数'),
        ),
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='white_active',
            field=models.BooleanField(default=False, verbose_name='是否开启白名单'),
        ),
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='white_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), default=list, size=None, verbose_name='白名单列表'),
        ),
    ]
