# Generated by Django 4.1.10 on 2023-12-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_api_key_is_active_alter_application_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='api_key_is_active',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否开启'),
        ),
    ]
