# Generated by Django 4.1.13 on 2024-06-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_chat_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('SIMPLE', '简易'), ('WORK_FLOW', '工作流')], default='SIMPLE', max_length=256, verbose_name='应用类型'),
        ),
        migrations.AddField(
            model_name='application',
            name='work_flow',
            field=models.JSONField(default=dict, verbose_name='工作流数据'),
        ),
    ]
