# Generated by Django 4.1.13 on 2024-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_application_type_application_work_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_ready',
            field=models.BooleanField(default=True, verbose_name='是否就绪'),
        ),
    ]
