# Generated by Django 4.1.10 on 2023-12-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_chatrecord_dataset_alter_chatrecord_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='improve_problem_id_list',
            new_name='improve_paragraph_id_list',
        ),
        migrations.AlterField(
            model_name='applicationaccesstoken',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.application', verbose_name='应用id'),
        ),
    ]
