# Generated by Django 4.2.13 on 2024-07-15 15:52

from django.db import migrations, models

import common.encoder.encoder


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0009_application_type_application_work_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='details',
            field=models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='对话详情'),
        ),
    ]
