# Generated by Django 4.1.13 on 2024-06-18 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_ready',
        ),
        migrations.CreateModel(
            name='WorkFlowVersion',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('work_flow', models.JSONField(default=dict, verbose_name='工作流数据')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'application_work_flow_version',
            },
        ),
    ]
