# Generated by Django 4.1.10 on 2023-12-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_model_provider'),
        ('application', '0010_rename_improve_problem_id_list_chatrecord_improve_paragraph_id_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.model'),
        ),
    ]
