# Generated by Django 4.2.15 on 2024-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_chatrecord_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='model_params_setting',
            field=models.JSONField(default=dict, verbose_name='模型参数相关设置'),
        ),
    ]
