# Generated by Django 5.2.11 on 2026-03-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_application_skill_tool_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapikey',
            name='user',
        ),
    ]
