# Generated by Django 5.2.13 on 2026-04-20 07:51

import django.db.models.deletion
from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_applicationapikey_user'),
        ('models_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='long_term_enable',
            field=models.BooleanField(default=False, verbose_name='长期记忆是否开启'),
        ),
        migrations.AddField(
            model_name='application',
            name='long_term_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_term_model_id', to='models_provider.model'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='long_term_enable',
            field=models.BooleanField(default=False, verbose_name='长期记忆是否开启'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='long_term_model_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='长期记忆模型id'),
        ),
        migrations.AddField(
            model_name='application',
            name='long_term_model_params_setting',
            field=models.JSONField(default=dict, verbose_name='长期记忆模型参数相关设置'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='long_term_model_params_setting',
            field=models.JSONField(default=dict, verbose_name='长期记忆模型参数相关设置'),
        ),
        migrations.AddField(
            model_name='application',
            name='long_term_trigger_setting',
            field=models.JSONField(default=dict, verbose_name='长期记忆触发配置'),
        ),
        migrations.AddField(
            model_name='application',
            name='long_term_trigger_type',
            field=models.CharField(default='ROUND', verbose_name='长期记忆触发类型'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='long_term_trigger_setting',
            field=models.JSONField(default=dict, verbose_name='长期记忆触发配置'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='long_term_trigger_type',
            field=models.CharField(default='ROUND', verbose_name='长期记忆触发类型'),
        ),
        migrations.CreateModel(
            name='ApplicationLongTermMemory',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id',
                 models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False,
                                  verbose_name='主键id')),
                ('chat_user_id', models.CharField(db_index=True, max_length=128, verbose_name='对话用户id')),
                ('memory', models.TextField(default='', verbose_name='长期记忆内容')),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE,
                                                  to='application.application', verbose_name='所属应用')),
            ],
            options={
                'db_table': 'application_long_term_memory',
                'indexes': [
                    models.Index(fields=['application_id', 'chat_user_id'], name='application_applica_7a56a7_idx')],
                'unique_together': {('application', 'chat_user_id')},
            },
        ),
    ]
