# Generated by Django 5.2.9 on 2026-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_long_term_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.CharField(null=True, max_length=128, verbose_name='应用代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='application_code',
            field=models.CharField(null=True, max_length=128, verbose_name='应用代码'),
            preserve_default=False,
        ),
    ]