# Generated by Django 5.2.14 on 2026-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_long_term_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='workflow_context',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='工作流上下文'),
        ),
    ]
