# Generated by Django 5.2.15 on 2026-07-29 02:42

from django.db import migrations, models


def forwards(apps, schema_editor):
    Application = apps.get_model("application", "Application")
    ResourceMapping = apps.get_model("system_manage", "ResourceMapping")
    ApplicationVersion = apps.get_model("application", "ApplicationVersion")

    APPLICATION = "APPLICATION"
    KNOWLEDGE = "KNOWLEDGE"
    SIMPLE = "SIMPLE"
    db_alias = schema_editor.connection.alias
    simple_application_ids = {
        str(app_id)
        for app_id in Application.objects.using(db_alias)
        .filter(type=SIMPLE)
        .values_list("id", flat=True)
    }
    mapping = {}
    qs = (
        ResourceMapping.objects.using(db_alias)
        .filter(source_type=APPLICATION, target_type=KNOWLEDGE)
        .values_list("source_id", "target_id")
    )
    for source_id, target_id in qs.iterator():
        if source_id in simple_application_ids:
            mapping.setdefault(source_id, []).append(target_id)
    mapping = {k: list(dict.fromkeys(v)) for k, v in mapping.items()}

    updates = []
    for obj in ApplicationVersion.objects.using(db_alias).iterator():
        app_id = str(obj.application_id)
        if app_id not in simple_application_ids:
            continue
        knowledge_ids = mapping.get(app_id)
        if knowledge_ids:
            obj.knowledge_ids = knowledge_ids
            updates.append(obj)
    if updates:
        ApplicationVersion.objects.using(db_alias).bulk_update(
            updates, ["knowledge_ids"], batch_size=500
        )


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_long_term_enable_and_more'),
        ('system_manage', '0005_resourcemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationversion",
            name="knowledge_ids",
            field=models.JSONField(default=list, verbose_name="数据集id列表"),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
