# Generated by Django 5.2.16 on 2026-08-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_applicationversion_knowledge_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='default_model_setting',
            field=models.JSONField(default=dict, verbose_name='默认模型设置'),
        ),
    ]
