# Generated by Django 5.2.14 on 2026-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_chatrecord_workflow_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='execute_type',
            field=models.CharField(choices=[('ANONYMOUS_USER', '匿名用户'), ('CHAT_USER', '对话用户'), ('SYSTEM_API_KEY', '系统API_KEY'), ('APPLICATION_API_KEY', '应用API_KEY'), ('PLATFORM_USER', '平台用户')], default='CHAT', max_length=64, verbose_name='执行类型'),
        ),
    ]
