# Generated by Django 4.2.15 on 2024-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_re_database_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='problem_text',
            field=models.CharField(max_length=10240, verbose_name='问题'),
        ),
    ]
