# Generated by Django 5.2.14 on 2026-07-22 08:33

import common.encoder.encoder
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_chat_execute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None, verbose_name='响应message'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='question',
            field=models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='用户的消息'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
    ]
