# Generated by Django 6.1 on 2026-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_chatrecord_messages_chatrecord_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_portal",
            field=models.BooleanField(default=False, verbose_name="是否在门户上架"),
        )
    ]
