# Generated by Django 4.2.15 on 2024-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_chatrecord_problem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tts_model_params_setting',
            field=models.JSONField(default=dict, verbose_name='模型参数相关设置'),
        ),
    ]
