# Generated by Django 4.2.15 on 2024-10-16 15:17

from django.db import migrations, models

sql = """
UPDATE "public".application_work_flow_version
SET "name" =  TO_CHAR(create_time, 'YYYY-MM-DD HH24:MI:SS');
"""


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0016_alter_chatrecord_problem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='版本名称'),
        ),
        migrations.RunSQL(sql)
    ]
