# Generated by Django 4.2.15 on 2024-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_application_tts_model_params_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='clean_time',
            field=models.IntegerField(default=180, verbose_name='清理时间'),
        ),
    ]
