# Generated by Django 6.1 on 2026-09-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0017_application_is_portal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="default_model_setting",
            field=models.JSONField(default=dict, verbose_name="默认模型"),
        ),
        migrations.AddField(
            model_name="applicationversion",
            name="default_model_setting",
            field=models.JSONField(default=dict, verbose_name="默认模型"),
        ),
        migrations.AlterField(
            model_name="applicationchatuserstats",
            name="chat_user_type",
            field=models.CharField(
                choices=[
                    ("ANONYMOUS_USER", "匿名用户"),
                    ("CHAT_USER", "对话用户"),
                    ("SYSTEM_API_KEY", "系统API_KEY"),
                    ("APPLICATION_API_KEY", "应用API_KEY"),
                    ("PLATFORM_USER", "平台用户"),
                    ("SYSTEM_USER", "系统用户"),
                ],
                default="ANONYMOUS_USER",
                max_length=64,
                verbose_name="对话用户类型",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_user_type",
            field=models.CharField(
                choices=[
                    ("ANONYMOUS_USER", "匿名用户"),
                    ("CHAT_USER", "对话用户"),
                    ("SYSTEM_API_KEY", "系统API_KEY"),
                    ("APPLICATION_API_KEY", "应用API_KEY"),
                    ("PLATFORM_USER", "平台用户"),
                    ("SYSTEM_USER", "系统用户"),
                ],
                default="ANONYMOUS_USER",
                max_length=64,
                verbose_name="客户端类型",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="execute_type",
            field=models.CharField(
                choices=[
                    ("ANONYMOUS_USER", "匿名用户"),
                    ("CHAT_USER", "对话用户"),
                    ("SYSTEM_API_KEY", "系统API_KEY"),
                    ("APPLICATION_API_KEY", "应用API_KEY"),
                    ("PLATFORM_USER", "平台用户"),
                    ("SYSTEM_USER", "系统用户"),
                ],
                default="CHAT",
                max_length=64,
                verbose_name="执行类型",
            ),
        ),
    ]
