# Generated by Django 4.2.15 on 2024-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_workflowversion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_upload_enable',
            field=models.BooleanField(default=False, verbose_name='文件上传是否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_upload_setting',
            field=models.JSONField(default={}, verbose_name='文件上传相关设置'),
        ),
    ]
