# Generated by Django 4.2.15 on 2024-11-13 10:13

import django.contrib.postgres.fields
from django.db import migrations, models

sql = """
UPDATE application_chat_record
SET answer_text_list=ARRAY[jsonb_build_object('content',answer_text)]
"""


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0018_workflowversion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_upload_enable',
            field=models.BooleanField(default=False, verbose_name='文件上传是否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_upload_setting',
            field=models.JSONField(default=dict, verbose_name='文件上传相关设置'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='answer_text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None, verbose_name='改进标注列表')
        ),
        migrations.RunSQL(sql)
    ]
