# Generated by Django 6.1 on 2026-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0018_application_default_model_setting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationversion",
            name="publish_desc",
            field=models.CharField(default="", max_length=1024, verbose_name="更新说明"),
        ),
    ]
