# Generated by Django 4.2.15 on 2024-12-27 18:42

from django.db import migrations, models
import uuid

run_sql = """
UPDATE application_public_access_client
SET client_id="id"
"""


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0020_application_record_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpublicaccessclient',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='公共访问链接客户端id'),
        ),
        migrations.AlterField(
            model_name='applicationpublicaccessclient',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False,
                                   verbose_name='主键id'),
        ),
        migrations.AddIndex(
            model_name='applicationpublicaccessclient',
            index=models.Index(fields=['client_id'], name='application_client__4de9af_idx'),
        ),
        migrations.RunSQL(run_sql)
    ]
