# Generated by Django 4.2.15 on 2025-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0023_application_stt_autosend'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='language',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='语言')
        ),
    ]
