# Generated by Django 4.2.15 on 2025-01-20 06:59

import application.models.api_key_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_application_stt_autosend'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccesstoken',
            name='language',
            field=models.CharField(default=application.models.api_key_model.get_language, max_length=10, verbose_name='语言'),
        ),
    ]
