# Generated by Django 4.2.18 on 2025-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_application_prologue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaccesstoken',
            name='language',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='语言'),
        ),
    ]
