# Generated by Django 4.2.18 on 2025-03-18 06:05

import application.models.application
import common.encoder.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_application_prologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='asker',
            field=models.JSONField(default=application.models.application.default_asker, encoder=common.encoder.encoder.SystemEncoder, verbose_name='访问者'),
        ),
    ]
