# Generated by Django 4.2.18 on 2025-03-18 06:05

import application.models.application
import common.encoder.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_chat_asker'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['create_time'], name='application_chat_create_time_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecord',
            index=models.Index(fields=['create_time'], name='application_chat_record_update_time_idx'),
        ),
    ]

