# Generated by Django 5.2.1 on 2025-06-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='workspace_id',
            field=models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id'),
        ),
    ]
