"""Shared MCP configuration types and validation."""


class InternalMCPConfig(dict):
    """In-memory provenance for configurations generated by ToolExecutor.

    Never deserialize user input into this type. JSON round trips deliberately
    lose this privilege; keep runtime configurations in memory instead.
    """


def validate_mcp_servers(servers):
    if not isinstance(servers, dict):
        raise ValueError("MCP servers must be an object")
    for config in servers.values():
        if not isinstance(config, dict) or config.get("transport") not in ("sse", "streamable_http"):
            raise ValueError("Only support transport=sse or transport=streamable_http")
        if not isinstance(config.get("url"), str) or not config["url"].strip():
            raise ValueError("MCP server URL must be a non-empty string")
