"""Shared MCP configuration types and validation."""

import json


REMOTE_FIELDS = {"transport", "url", "headers", "timeout", "sse_read_timeout", "terminate_on_close"}


class InternalMCPConfig(dict):
    """In-memory provenance for configurations generated by ToolExecutor.

    Never deserialize user input into this type. JSON round trips deliberately
    lose this privilege; keep runtime configurations in memory instead.
    """


def validate_mcp_servers(servers):
    if not isinstance(servers, dict):
        raise ValueError("MCP servers must be an object")
    for config in servers.values():
        if not isinstance(config, dict) or config.get("transport") not in ("sse", "streamable_http"):
            raise ValueError("Only support transport=sse or transport=streamable_http")
        if not isinstance(config.get("url"), str) or not config["url"].strip():
            raise ValueError("MCP server URL must be a non-empty string")


def remote_connection(config):
    """Copy serializable transport data, excluding commands and SDK callbacks."""
    remote = {key: value for key, value in config.items() if key in REMOTE_FIELDS}
    if remote.get("transport") == "sse":
        remote.pop("terminate_on_close", None)
    return json.loads(json.dumps(remote, allow_nan=False))
