# Generated by Django 5.2.9 on 2026-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggertask',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='triggertask',
            name='parameter',
            field=models.JSONField(default=list),
        ),
    ]
