# Generated by Django 5.2.9 on 2026-01-26 03:27

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='trigger_task',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='trigger_task_id',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, verbose_name='触发器任务id'),
        ),
    ]
