# Generated by Django 5.2.9 on 2026-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_taskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='task_record_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='任务记录id'),
        ),
    ]
