# Generated by Django 5.2.9 on 2026-01-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0003_alter_taskrecord_task_record_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triggertask',
            unique_together={('trigger', 'source_id', 'source_type')},
        ),
    ]
