on:
  push:
    branches:    
      - 'pr@**'
      - 'repr@**'

name: 针对特定分支名自动创建 PR

jobs:
  generic_handler:
    name: 自动创建 PR
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: jumpserver/action-generic-handler@60f2d663e639907248d5baf7b1b5c2cbf2ac9e60 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
