on:
  push:
    branches:    
      - 'pr@**'
      - 'repr@**'

name: Automatically create PRs for specific branch names

jobs:
  generic_handler:
    name: Auto create PR
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: jumpserver/action-generic-handler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
