FROM postgres:15.6-bookworm

ARG DEPENDENCIES="                    \
        curl                          \
        vim                           \
        python3.11-mini               \
        python3.11-venv               \
        postgresql-15-pgvector"

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get update && apt-get install -y --no-install-recommends $DEPENDENCIES && \
    apt-get clean all  && \
    rm -rf /var/lib/apt/lists/*